### ISSUE TITLE
Specify minimum nodejs requirements

### ISSUE THREAD

**Issue by anselmbradford** [zoubin/gulp-watchify-factor-bundle#1]
Using the supplied example, https://github.com/zoubin/gulp-watchify-factor-bundle/blob/master/index.js#L51 returns `ReferenceError: Promise is not defined`. I upgraded npm and the error went away. Unfortunately I didn't get a chance to check what nodejs version I was running, but npm was `2.1.18` before updating to `2.12.1` and having the error disappear.

**Comment by zoubin** [comment]
I have refactored the code. The latest version (1.0.0) no longer uses promise.

**Comment by anselmbradford** [comment]
Cool, feel free to close unless there's still a minimum nodejs requirement.
